[WIP] Improve changelog style (#11)
* Remove Python 2 compatibility.

* Add module docstrings.

* Linting.

* Add mypy linting.

* Continue with linting, type hints and doc strings.

* Add stubs to pyre search path.

* Move all resolver code to changes.py.

* Rewrite resolvers and resolve usage to make type checking easier.

* Add linting scripts, and use them in CI.

diff --git a/.github/workflows/pythonlinters.yml b/.github/workflows/pythonlinters.yml
--- a/.github/workflows/pythonlinters.yml
+++ b/.github/workflows/pythonlinters.yml
@@ -31,15 +31,21 @@ jobs:
 
       - name: Lint with flake8
         run: |
-          poetry run flake8 ansibulled --count --max-complexity=10 --max-line-length=100 --statistics
+          ./lint-flake8.sh
 
       - name: Lint with pyre
         run: |
-          poetry run pyre --source-directory ansibulled --search-path $(poetry run python -c 'from distutils.sysconfig import get_python_lib;print(get_python_lib())')
+          ./lint-pyre.sh
         if: always()
 
       # note: pylint is run informationally, never to fail the build
       - name: Lint with pylint
         run: |
-          poetry run pylint ansibulled || :
+          ./lint-pylint.sh || :
+        if: always()
+
+      # note: mypy is run informationally, never to fail the build
+      - name: Lint with mypy
+        run: |
+          ./lint-mypy.sh || :
         if: always()
