Update dependencies and add more checking
* I got the okay to require python-3.6+ for the docs build so we now
  require that.
* Install pyre via poetry so that we can manage our type checker via
  poetry
  * Run pyre under poetry in our linting github action
* Make flake8 fail the build as it has a managable amount of complaining
  (We can either comply or tell it no)
* Run pylint via the linter in an advisory capacity

diff --git a/.github/workflows/pythonlinters.yml b/.github/workflows/pythonlinters.yml
--- a/.github/workflows/pythonlinters.yml
+++ b/.github/workflows/pythonlinters.yml
@@ -6,9 +6,9 @@ name: Python linting
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   build:
@@ -18,29 +18,28 @@ jobs:
         python-version: [3.8]
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v1
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install poetry
-        poetry install
-        # pyre requires python-3.8+ and poetry doesn't know that we're only testing under python-3.8
-        python -m pip install pyre-check
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install poetry
+          poetry install
 
-    # For now pylint is run on codacy
+      - name: Lint with flake8
+        run: |
+          poetry run flake8 ansibulled --count --max-complexity=10 --max-line-length=100 --statistics
 
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        poetry run flake8 ansibulled --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings.
-        poetry run flake8 ansibulled --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
+      - name: Lint with pyre
+        run: |
+          poetry run pyre --source-directory ansibulled --search-path $(poetry run python -c 'from distutils.sysconfig import get_python_lib;print(get_python_lib())')
+        if: always()
 
-    - name: Lint with pyre
-      run: |
-        pyre --source-directory ansibulled --search-path $(poetry run python -c 'from distutils.sysconfig import get_python_lib;print(get_python_lib())')
-      if: always()
+      # note: pylint is run informationally, never to fail the build
+      - name: Lint with pylint
+        run: |
+          poetry run pylint ansibulled || :
+        if: always()
